// Get query from input 

var newsquery = document.querySelector(".gnews-query")
var gnews = encodeURI(newsquery.value);

// Get Month/Date/Year from Input 

var ddrop = document.querySelector(".daycut").value;
var mdrop = document.querySelector(".monthcut").value;
var ydrop = document.querySelector(".yearcut").value;


// stop counting year from 0
ydrop = ydrop+1; 

//calculate number of days per unit
 var dcounter = ddrop  * 1;
// Note this just counts a month as 30 days no matter what, so it's imprecise, but close
// enough for what we're doing
var mcounter = mdrop  * 30;
var ycounter = ydrop  * 365;


var dayscounter = dcounter + mcounter + ycounter;


// setting up URL components

var baseGN = "https://www.google.com/search";
var datepre = "&tbs=cdr:1,"
var mindate = "cd_min:1/1/1900,"
// maxdate generated by function
var source = "&tbm=nws&source=hp"

// Assembling and Opening the URL for Each Function 

function day_search(){
  
  var newsquery = document.querySelector(".gnews-query")
  var gnews = encodeURI(newsquery.value);
  var query = "?q="+gnews;
  var ddrop = document.querySelector(".daycut").value;
  var dcounter = ddrop  * 1;
  var daySearch = document.querySelector(".daysis")
  var baseDate = new Date();
  baseDate.setDate(baseDate.getDate() - dcounter);
  var yyyy = baseDate.getFullYear();
  var mm = baseDate.getMonth();
  mm = mm+1; //Otherwise the month will be one off because the counting starts at 0
  var dd = baseDate.getDate();
  var cdmax = "cd_max:"+mm+"/"+dd+"/"+yyyy
  var fullSearch=baseGN+query+source+datepre+mindate+cdmax;
   window.open(fullSearch);
  
  
}

function month_search(){
  
  var newsquery = document.querySelector(".gnews-query")
  var gnews = encodeURI(newsquery.value);
  var query = "?q="+gnews;
  var mdrop = document.querySelector(".monthcut").value;
  var mdrop = mdrop;
  var dcounter = mdrop  * 30;
  var baseDate = new Date();
  baseDate.setDate(baseDate.getDate() - dcounter);
   var yyyy = baseDate.getFullYear();
  var mm = baseDate.getMonth();
  var mm = mm+1;
  var mcounter = mm  * 30;
  var dd = baseDate.getDate();
  var cdmax = "cd_max:"+mm+"/"+dd+"/"+yyyy
  var fullSearch=baseGN+query+source+datepre+mindate+cdmax;
   window.open(fullSearch);
  
  
}



function year_search(){
  
  var newsquery = document.querySelector(".gnews-query")
  var gnews = encodeURI(newsquery.value);
  var query = "?q="+gnews;
  var ydrop = document.querySelector(".yearcut").value;
  var dcounter = ydrop  * 365;
  var baseDate = new Date();
  baseDate.setDate(baseDate.getDate() - dcounter);
  var yyyy = baseDate.getFullYear();
  var mm = baseDate.getMonth();
  var mm = mm+1;
  var dd = baseDate.getDate();
  var cdmax = "cd_max:"+mm+"/"+dd+"/"+yyyy
   var fullSearch=baseGN+query+source+datepre+mindate+cdmax;
   window.open(fullSearch);
  
  
}

